#cloud-config

datasource:
  Ec2:
    timeout: 60
    max_wait: 60
    metadata_urls:
      - http://169.254.169.254
      - http://instance-data

package_update: true
package_upgrade: true

packages:
- docker.io
- jq
- awscli
- openjdk-8-jdk-headless

write_files:
- path: /etc/aws/aws.conf
  permissions: '0644'
  content: |
    [Global]
    Zone = ${aws_region}
- path: /etc/elasticsearch/elasticsearch.yml
  permissions: '0664'
  content: |
    # elasticsearch configuration file
    cluster:
      name: ${cluster_id}
      routing.allocation.awareness.attributes: aws_availability_zone
    node:
      name: _ec2:privateDns_
      master: true
      data: true
    cloud:
      node.auto_attributes: true
    discovery:
      ec2:
        availability_zones: ${aws_availability_zones}
        node_cache_time: 120s
        groups: ${es_discovery_sg}
      zen:
        hosts_provider: ec2
        join_timeout: 600s
        ping_timeout: 60s
    http.port: 9200
    transport.tcp.port: 9300
    network.host:
    - _site_
    - _ec2_
    network.publish_host: _ec2:privateIp_
    plugin.mandatory:
    - discovery-ec2
    - repository-s3
- path: /etc/default/elasticsearch
  permissions: '0644'
  content: |
    # elasticsearch configure options
- path: /var/lib/elasticsearch/Dockerfile
  permissions: '0644'
  content: |
    FROM docker.elastic.co/elasticsearch/elasticsearch:${es_version}
    RUN bin/elasticsearch-plugin remove x-pack && \
        bin/elasticsearch-plugin install -b discovery-ec2 && \
        bin/elasticsearch-plugin install -b repository-s3
- path: /etc/default/elasticsearch-stunnel-http
  permissions: '0644'
  content: |
    # elasticsearch-stunnel-http configure options
    STUNNEL_SERVICE=elasticsearch-http
    STUNNEL_ACCEPT=${tls_http_port}
    STUNNEL_CONNECT=localhost:${http_port}
- path: /etc/default/elasticsearch-stunnel-transport
  permissions: '0644'
  content: |
    # elasticsearch-stunnel-transport configure options
    STUNNEL_SERVICE=elasticsearch-transport
    STUNNEL_ACCEPT=${tls_transport_port}
    STUNNEL_CONNECT=localhost:${transport_port}
- path: /etc/default/elasticsearch-cerebro
  permissions: '0644'
- path: /etc/systemd/system/elasticsearch.service
  permissions: '0644'
  content: |
    [Unit]
    Description=The ElasticSearch container
    After=docker.service
    Requires=docker.service
    PartOf=docker.service
    [Service]
    EnvironmentFile=/etc/default/elasticsearch
    ExecStartPre=-/usr/bin/docker rm -f elasticsearch
    ExecStart=/usr/bin/docker run --name elasticsearch --hostname $(hostname).${cluster_id} --rm -v /var/lib/elasticsearch:/var/lib/elasticsearch:z -v /usr/share/elasticsearch/config:/usr/share/elasticsearch/config:z --env-file=/etc/default/elasticsearch --network=host -p ${http_port}:${http_port} -p ${transport_port}:${transport_port} elasticsearch:${es_version}
    ExecStop=/usr/bin/docker stop elasticsearch
    SyslogIdentifier=elasticsearch
    Restart=always
    RestartSec=5s
    [Install]
    WantedBy=docker.service
- path: /etc/systemd/system/elasticsearch-stunnel-http.service
  permissions: '0644'
  content: |
    [Unit]
    Description=The ElasticSearch STunnel HTTP container
    After=elasticsearch.service
    Requires=elasticsearch.service
    PartOf=docker.service
    [Service]
    EnvironmentFile=/etc/default/elasticsearch-stunnel-http
    ExecStartPre=-/usr/bin/docker rm -f elasticsearch-stunnel-http
    ExecStart=/usr/bin/docker run --name elasticsearch-stunnel-http --hostname $(hostname).${cluster_id} --rm -v /etc/stunnel:/etc/stunnel:z --env-file=/etc/default/elasticsearch-stunnel-http --network=host -p ${tls_http_port}:${tls_http_port} dweomer/stunnel
    ExecStop=/usr/bin/docker stop elasticsearch-stunnel-http
    SyslogIdentifier=elasticsearch-stunnel-http
    Restart=always
    RestartSec=5s
    [Install]
    WantedBy=docker.service
- path: /etc/systemd/system/elasticsearch-stunnel-transport.service
  permissions: '0644'
  content: |
    [Unit]
    Description=The ElasticSearch STunnel HTTP container
    After=elasticsearch.service
    Requires=elasticsearch.service
    PartOf=docker.service
    [Service]
    EnvironmentFile=/etc/default/elasticsearch-stunnel-transport
    ExecStartPre=-/usr/bin/docker rm -f elasticsearch-stunnel-transport
    ExecStart=/usr/bin/docker run --name elasticsearch-stunnel-transport --hostname $(hostname).${cluster_id} --rm -v /etc/stunnel:/etc/stunnel:z --env-file=/etc/default/elasticsearch-stunnel-transport --network=host -p ${tls_transport_port}:${tls_transport_port} dweomer/stunnel
    ExecStop=/usr/bin/docker stop elasticsearch-stunnel-transport
    SyslogIdentifier=elasticsearch-stunnel-transport
    Restart=always
    RestartSec=5s
    [Install]
    WantedBy=docker.service
- path: /etc/systemd/system/elasticsearch-cerebro.service
  permissions: '0644'
  content: |
    [Unit]
    Description=The ElasticSearch Cerebro container
    After=elasticsearch.service
    Requires=elasticsearch.service
    PartOf=docker.service
    [Service]
    EnvironmentFile=/etc/default/elasticsearch-cerebro
    ExecStartPre=-/usr/bin/docker rm -f elasticsearch-cerebro
    ExecStart=/usr/bin/docker run --name elasticsearch-cerebro --hostname $(hostname).${cluster_id} --rm --env-file=/etc/default/elasticsearch-cerebro --network=host -p ${cerebro_port}:${cerebro_port} yannart/cerebro:${cerebro_version}
    ExecStop=/usr/bin/docker stop elasticsearch-cerebro
    SyslogIdentifier=elasticsearch-cerebro
    Restart=always
    RestartSec=5s
    [Install]
    WantedBy=docker.service
- path: /etc/stunnel/stunnel.key
  permissions: '0600'
- path: /etc/stunnel/stunnel.pem
  permissions: '0640'

runcmd:
- export AWS_DEFAULT_REGION=${aws_region}
- INSTANCE_ID=$(curl -Lfs http://169.254.169.254/latest/meta-data/instance-id)
- >
  echo '{
    "Comment": "auto updated @ '$(date)'",
    "Changes": [{
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "'$(curl -Lfs http://169.254.169.254/latest/meta-data/local-hostname)'",
        "Type": "A",
        "TTL": 60,
        "ResourceRecords": [{
          "Value": "'$(curl -Lfs http://169.254.169.254/latest/meta-data/local-ipv4)'"
        }]
      }
    }]
  }' > /tmp/route53_update.json &&
  aws route53 change-resource-record-sets --hosted-zone-id ${dns_zone_id} --change-batch file:///tmp/route53_update.json
- echo '${tls_key}' > /etc/stunnel/stunnel.key
- echo '${tls_cert}' > /etc/stunnel/stunnel.pem
- sysctl -w vm.max_map_count=262144
- mkdir -p /usr/share/elasticsearch
- curl "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${es_version}.tar.gz" | tar xzf - -C /usr/share/elasticsearch --strip 1
- for P in ingest-user-agent ingest-geoip discovery-ec2 repository-s3; do /usr/share/elasticsearch/bin/elasticsearch-plugin install -b $P; done
- ln -snf /etc/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
- chown -R 1000:1000 /usr/share/elasticsearch
- docker build --no-cache --pull --tag elasticsearch:${es_version} -f /var/lib/elasticsearch/Dockerfile /var/lib/elasticsearch
- systemctl daemon-reload
- systemctl enable elasticsearch elasticsearch-stunnel-http elasticsearch-stunnel-transport elasticsearch-cerebro
- systemctl start elasticsearch elasticsearch-stunnel-http elasticsearch-stunnel-transport elasticsearch-cerebro
